import { siteConfig } from "@/config/site";

export const metadata = {
  title: `About & Disclosures — ${siteConfig.name}`,
};

export default function About() {
  return (
    <div className="wrap max-w-prose font-serif leading-relaxed">
      <h1 className="display text-3xl font-semibold">About {siteConfig.name}</h1>

      <p className="mt-5 text-ink/90">
        {siteConfig.name} reads documents you&apos;re about to sign and explains
        them in plain, friendly English — who the contract benefits, what
        you&apos;re agreeing to, and the parts worth a second look. The goal is
        simple: help you understand what&apos;s in front of you before you put
        your name on it.
      </p>

      <h2 className="display mt-10 text-xl font-semibold">
        This is not legal advice
      </h2>
      <p className="mt-3 text-ink/90">
        {siteConfig.name} is an automated, plain-English summary tool. It is{" "}
        <strong>not a law firm</strong>, it does not provide legal advice, and
        using it does not create an attorney–client relationship. The summaries
        are generated by AI and may be incomplete or mistaken. They are not a
        substitute for review by a qualified attorney licensed in your
        jurisdiction. For decisions that matter, consult a lawyer. You are
        responsible for any choices you make about a document.
      </p>

      <h2 className="display mt-10 text-xl font-semibold">Your documents</h2>
      <p className="mt-3 text-ink/90">
        Documents you submit are sent to our AI provider to generate the
        summary. When red flags are found, an anonymized record — the company or
        party name and the issues spotted — may be added to our searchable
        database so others can benefit. We do not publish the full text of your
        document. Avoid uploading documents containing sensitive personal
        information you don&apos;t want processed.
      </p>

      <h2 className="display mt-10 text-xl font-semibold">Contact</h2>
      <p className="mt-3 text-ink/90">
        {siteConfig.name} is operated by {siteConfig.operator}. Questions or
        concerns:{" "}
        <a className="text-flag underline" href={`mailto:${siteConfig.contactEmail}`}>
          {siteConfig.contactEmail}
        </a>
        .
      </p>
    </div>
  );
}
